### ISSUE TITLE
Layout / border-box

### ISSUE THREAD

**Issue by ludoo0d0a** [ThemeBoy/Rookie#28]
since a few days (may be last updates), 2 columns (2/3 1/3) cannot fit on the same row, and in photo gallery, names under photo are too long too.

If I add this, the layout is fixed (but I don't know what happend since last version, and why  ) : 

```css
.content-area, 
.widget-area,
.gallery .gallery-item *{
	-webkit-box-sizing: border-box; 
	-moz-box-sizing: border-box;  
	box-sizing: border-box;  
}
```
